- name: check if the hello-stone project has been cloned before
  stat:
    path: /home/ubuntu/hello-stone
  register: stat_result

- name:  get the hello-stone project from github repo
  git:
    repo: "https://github.com/jbiers/desafio-stone.git"
    dest: /home/ubuntu/desafio-stone
    version: main
  when: not stat_result.stat.exists