- name: install docker dependencies
  apt:
    update_cache: yes
    name: [
        apt-transport-https,
        ca-certificates,
        curl,
        gnupg-agent,
        software-properties-common,
        gnupg-agent,
        gnupg,
        lsb-release
    ]

- name: add gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: actually install docker
  apt:
    name: [
      "docker-ce",
      "docker-ce-cli",
      "containerd.io"
    ]
    update_cache: yes

